### PR TITLE
Fix repository GitHub username

### PR DESCRIPTION
**Pull request by iamandrewluca**

### CODE REVIEW

**Comment by gustavoguichard** [comment]
@iamandrewluca I see a pattern here <3

**Comment by iamandrewluca** [comment]
@gustavoguichard I'm using https://njt.vercel.app/ to jump to packages repos, and when I try some package, and it shows a 404, then I go to fix the repo 🙂

**Comment by gustavoguichard** [comment]
@iamandrewluca thank you TIL !!
Awesome tool!

FWIW: I always make sure to check packages on https://pkg-size.dev/string-ts so I know the actual size after tree shaking and cherry-picking just what I want.

**Comment by gustavoguichard** [comment]
@all-contributors please add @iamandrewluca for doc.

**Pull request merged**
